name: build-vscode-artifact

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
    paths:
      - 'sdks/vscode/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Install dependencies
        run: bun install
        working-directory: ./sdks/vscode

      - name: Build and Package VSIX
        run: |
          bun run package
          npx @vscode/vsce package --no-git-tag-version --no-update-package-json --skip-license -o dist/innexarcode.vsix
        working-directory: ./sdks/vscode

      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: innexarcode-extension
          path: sdks/vscode/dist/innexarcode.vsix
